### ISSUE TITLE
Install option

### ISSUE THREAD

**Issue by rever96** [burakoner/Tatum.Net#3]
Hi, I want to try this sdk with Unity, 
I'm having trouble with using nuget in a Unity solution because Unity override the assembly and it removes your package every time.
Could you give another install option (maybe dll import)?

**Comment by burakoner** [comment]
This is  an open source library.  You can extract  dl files from nuget package, you can pull and edit  this repository.  Be creative

**Comment by rever96** [comment]
wow it compiles!
